server:
  port: 4010
  request:
    # 设定最大的上传文件大小
    maxFileSize: 10mb
    # 设定最大请求大小
    maxBodySize: 10mb
    # 设定上传使用临时文件，如果开启，文件将存到临时文件，不会占用内存，但需要手动清除临时文件，默认不开启，开启需要配置
    useTempfile: false
solon:
  env: dev
  app:
    name: superb-allocation-biz
    meta:
      version: "v1"
      author: "ajie"
  cloud:
    nacos2:
      server: "nacos.superb.com:8848"
      username: nacos
      password: nacos
      namespace: dev
      config:
        load: "application-${solon.env}.yml,${solon.app.name}-${solon.env}.yml"

solon.logging:
  logger:
    "com.alibaba.nacos":
      level: ERROR
    "org.redisson":
      level: ERROR
    "io.netty":
      level: ERROR
    "com.zaxxer.hikari":
      level: ERROR
    "org.apache.ibatis":
      level: ERROR
    "com.superb.allocation.mapper":
      level: INFO
  appender:
    console:
      level: TRACE
      enable: true #是否启用
      pattern: "[${solon.app.name}] %yellow([%d{yyyy-MM-dd HH:mm:ss.SSS}]) %blue([%thread]) %highlight([%level]) %green(%logger) %blue(Line:%L) - %cyan(%msg%n)"
    file:
      name: "logs/${solon.app.name}"
      pattern: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] [%thread] [%level] %logger Line:%L - %msg%n"
      level: INFO
      enable: true #是否启用
      extension: ".log"   #v2.2.18 后支持（例：.log, .log.gz, .log.zip）
      maxFileSize: "10 MB"
      maxHistory: "7"

